export function getStyles(theme) {
  return {
    container: {
      maxWidth: 800,
      margin: "auto",
      padding: 20,
      fontFamily: "Arial, sans-serif",
      background: theme.background,
      color: theme.color,
      minHeight: "100vh",
      transition: "background 0.3s, color 0.3s",
    },
    navBar: {
      display: "flex",
      gap: 20,
      alignItems: "center",
      marginBottom: 25,
      borderBottom: `1.5px solid ${theme.border}`,
      paddingBottom: 14,
    },
    navBtn: (active) => ({
      fontWeight: active ? "bold" : "normal",
      color: theme.btn,
      background: "none",
      border: 0,
      fontSize: 17,
      cursor: "pointer",
      textDecoration: active ? "underline" : "none",
      padding: 0,
    }),
    card: {
      background: theme.card,
      border: `1px solid ${theme.border}`,
      borderRadius: 6,
      padding: 15,
      marginBottom: 18,
    },
    header: { display: "flex", justifyContent: "space-between", marginBottom: 20 },
    btn: {
      padding: "6px 12px",
      margin: "0 4px",
      cursor: "pointer",
      borderRadius: 4,
      border: "none",
      background: theme.btn,
      color: "#fff",
    },
    btnDanger: { background: theme.btnDanger, color: "#fff" },
    btnSecondary: { background: theme.btnSecondary, color: "#fff" },
    input: {
      padding: 6,
      width: "100%",
      boxSizing: "border-box",
      marginBottom: 12,
      background: theme.card,
      color: theme.color,
      border: `1px solid ${theme.border}`,
      borderRadius: 4,
    },
    categoryHeader: {
      fontSize: 19,
      fontWeight: "bold",
      cursor: "pointer",
      userSelect: "none",
      marginTop: 18,
      background: theme.card,
      border: `1px solid ${theme.border}`,
      padding: 8,
      borderRadius: 4,
      display: "flex",
      justifyContent: "space-between",
      alignItems: "center",
    },
    timerRow: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
      padding: "8px 12px",
      borderBottom: `1px solid ${theme.border}`,
      fontSize: 16,
    },
    timerInfo: { flex: 1, marginLeft: 16 },
    progressBarContainer: {
      height: 10,
      background: "#333",
      borderRadius: 5,
      overflow: "hidden",
      marginTop: 6,
    },
    progressBar: {
      height: "100%",
      background: theme.progress,
      transition: "width 0.3s",
    },
    modalOverlay: {
      position: "fixed",
      top: 0,
      left: 0,
      height: "100%",
      width: "100%",
      backgroundColor: "rgba(0,0,0,0.4)",
      display: "flex",
      justifyContent: "center",
      alignItems: "center",
      zIndex: 1000,
    },
    modalContent: {
      backgroundColor: theme.card,
      color: theme.color,
      padding: 34,
      borderRadius: 10,
      maxWidth: 400,
      minWidth: 230,
      textAlign: "center",
    },
    alertMsg: {
      marginTop: 6,
      padding: 6,
      backgroundColor: theme.alert,
      borderRadius: 4,
      color: theme.alertText,
      fontSize: 13,
    },
    select: {
      padding: "7px",
      minWidth: 120,
      background: theme.card,
      color: theme.color,
      border: `1px solid ${theme.border}`,
      borderRadius: 4,
      marginBottom: 20,
    },
    themeSwitcher: {
      cursor: "pointer",
      fontWeight: "bold",
      border: 0,
      padding: "8px 12px",
      background: theme.btn,
      color: "#fff",
      borderRadius: 4,
    },
  };
}
